add age extractor
usc-isi-i2/dig-age-extractor pull request #1
Opened 2016-10-07 03:52 UTC by ZwEin27

2016-10-07 17:02 UTC, jasonslepicka requested changes
Looks good for the most part.  Just needs some cleanup

2016-10-07 17:02 UTC, jasonslepicka commented on digAgeExtractor/age_helper.py
> +if __name__ == '__main__':
This is already captured in a unit test, right?  Can we remove it?

2016-10-07 17:02 UTC, jasonslepicka commented on digAgeExtractor/ages.json
> +[
Is this file necessary any more?  I think we can safely remove it.

2016-10-07 17:02 UTC, jasonslepicka commented on test/annotate_jl.py
> +        # .append((node_text, sorted(list(set(correct))), sorted(list(set(correct)))))
Let's remove commented out code

2016-10-07 17:02 UTC, jasonslepicka commented on test/annotate_jl.py
> +def annotate(intput_path, output_path=None):
Can we add some asserts in here to make it a test?

2016-10-08 01:41 UTC, ZwEin27 commented on digAgeExtractor/ages.json
> +[
it's necessary for now since we need conduct some experiments based on these data and script to improve performance,:)

2016-10-08 01:42 UTC, ZwEin27 commented on digAgeExtractor/ages.json
> +[
I will remove these files later after

2016-10-11 22:06 UTC, jasonslepicka commented on test/annotate_jl.py
> +def annotate(intput_path, output_path=None):
I see you added test/annotate_jl.py to .gitignore, but it's still in the repo.  Did you run `git rm test/annotate_jl.py`?

2016-10-12 03:19 UTC, ZwEin27 commented on test/annotate_jl.py
> +def annotate(intput_path, output_path=None):
Hi Jason, sorry for late response, :p. I just removed the file and pushed the change.

2016-10-13 16:54 UTC, jasonslepicka approved these changes

2016-10-13 16:54 UTC, merged